# -*- coding: utf-8 -*-
{
    'name': "supermodulo",

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        Long description of module's purpose
    """,

    'author': "My Company",
    'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/master/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends':
[
'base',
'crm',
'project',
'stock',
'mrp',
'sale',
'stock_account',
'mail',
'account',
'account_asset',
'account_accountant',
'project_issue',
'note',
'purchase',
'hr',
'account_balance_reporting',
'account_balance_reporting_xlsx',
'account_banking_mandate',
'account_banking_pain_base',
'account_banking_sepa_direct_debit',
'account_bank_statement_import',
'account_budget',
'account_cancel',
'account_chart_update',
'account_due_list',
'account_due_list_payment_mode',
'account_fiscal_year_closing',
'account_invoice_constraint_chronology',
'account_payment_mode',
'account_payment_order',
'account_payment_partner',
'account_renumber',
'account_reversal',
'account_tax_balance',
'analytic',
'auth_crypt',
'auth_signup',
'barcodes',
'base',
'base_action_rule',
'base_iban',
'base_import',
'base_import_module',
'base_location',
'base_location_geonames_import',
'base_partner_sequence',
'base_setup',
'base_vat',
'board',
'bus',
'contacts',
'contract',
'contract_payment_mode',
'contract_show_invoice',
'contract_variable_quantity',
'crm_sector',
'date_range',
'decimal_precision',
'disable_odoo_online',
'document',
'document_page',
'fetchmail',
'knowledge',
'l10n_es',
'l10n_es_account_asset',
'l10n_es_account_balance_report',
'l10n_es_account_bank_statement_import_n43',
'l10n_es_account_fiscal_year_closing',
'l10n_es_account_invoice_sequence',
'l10n_es_aeat',
'l10n_es_aeat_mod111',
'l10n_es_aeat_mod115',
'l10n_es_aeat_mod303',
'l10n_es_aeat_mod349',    
'l10n_es_mis_report',    
'l10n_es_partner',
'l10n_es_toponyms',
'mass_editing',
'partner_sector',
'payment',
'payment_transfer',
'procurement',
'procurement_jit',
'product',
'project_task_default_stage',
'project_timeline',
'purchase_mrp',
'report',
'report_xlsx',
'resource',
'sale_crm',
'sale_mrp',
'sales_team',
'sale_stock',
'utm',
'web',
'web_calendar',
'web_decimal_numpad_dot',
'web_diagram',
'web_editor',
'web_export_view',
'web_kanban',
'web_kanban_gauge',
'web_planner',
'web_settings_dashboard',
'web_timeline',
'web_tour',
'calendar',
'l10n_es_vat_book',
'account_financial_report_qweb',

],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}
